### ISSUE TITLE
Fatal Error Dotenv

### ISSUE THREAD

**Issue by Li4rat** [Alecaddd/awps#74] opened 2021-02-02 19:06 UTC
Hi Alex,i need your helo, i started new project with last release of AWPS (oldest release worked for me), i run "local byflywheel" app for manage websites (it is like mamp), after the theme installation (moved at root, renamed and set .env file, moved at root and renamed the wp-config file, runned composer install) when i try to run my website i get this error:

Fatal error: Uncaught TypeError: Argument 1 passed to Dotenv\Dotenv::create() must be an instance of Dotenv\Repository\RepositoryInterface, string given, called in /Users/myusername/Local Sites/awps/app/public/wp-config.php on line 26 and defined in /Users/myusername/Local Sites/awps/app/public/wp-content/themes/awps/vendor/vlucas/phpdotenv/src/Dotenv.php on line 83

I don't know how to resolve it, is there something new i missed?

**Comment by manzurahmed** [comment] 2021-02-20 15:18
I created .env, renamed wp-config.php, run "composer install" and "npm install". When I try to run the WP installation, I get the following message,
---
Fatal error: Uncaught TypeError: Argument 1 passed to Dotenv\Dotenv::create() must be an instance of Dotenv\Repository\RepositoryInterface, string given, called in /opt/lampp/htdocs/wp_alecaddd_awps/wp-config.php on line 26 and defined in /opt/lampp/htdocs/wp_alecaddd_awps/wp-content/themes/awpstest/vendor/vlucas/phpdotenv/src/Dotenv.php:83 Stack trace: #0 /opt/lampp/htdocs/wp_alecaddd_awps/wp-config.php(26): Dotenv\Dotenv::create('/opt/lampp/htdo...') #1 /opt/lampp/htdocs/wp_alecaddd_awps/wp-load.php(37): require_once('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/wp_alecaddd_awps/wp-blog-header.php(13): require_once('/opt/lampp/htdo...') #3 /opt/lampp/htdocs/wp_alecaddd_awps/index.php(17): require('/opt/lampp/htdo...') #4 {main} thrown in /opt/lampp/htdocs/wp_alecaddd_awps/wp-content/themes/awpstest/vendor/vlucas/phpdotenv/src/Dotenv.php on line 83
---
Is there any work around?

**Comment by Alecaddd** [comment] 2021-02-27 02:32
Duplicate of #76

**Closed by Alecaddd** 2021-02-27 02:32 UTC
